-- View: vw_active_customers
-- Purpose: Identify customers with recent activity (last 30 days) and calculate engagement metrics
-- Business metric: Active customers in a rolling 30-day window, order frequency, recent revenue, recency (days since order)
-- Updated: Automatically recalculated on every query execution (real-time data freshness)
-- Used by: Customer Success Dashboard, Marketing Retention Campaigns, Executive Activity Monitoring
--
-- Columns:
--   customer_id: Unique customer identifier
--   customer_name: Display name of the customer
--   segment: Customer business tier / segment (e.g., Enterprise, Mid-Market, SMB, VIP, Consumer)
--   order_count_30d: Count of distinct completed orders placed within the last 30 days
--   revenue_30d: Total gross revenue generated by customer in the last 30 days
--   last_order_date: ISO timestamp of the customer's most recent order
--   days_since_order: Number of days elapsed since the customer's last order date

DROP VIEW IF EXISTS vw_active_customers;

CREATE VIEW vw_active_customers AS 
SELECT 
    c.customer_id, 
    c.customer_name, 
    c.segment, 
    COUNT(DISTINCT o.order_id) AS order_count_30d, 
    COALESCE(SUM(o.order_amount), 0.0) AS revenue_30d, 
    MAX(o.order_date) AS last_order_date, 
    CAST(ROUND(JULIANDAY(CURRENT_DATE) - JULIANDAY(MAX(o.order_date))) AS INTEGER) AS days_since_order 
FROM customers c 
LEFT JOIN orders o ON c.customer_id = o.customer_id 
                   AND o.order_date >= DATE(CURRENT_DATE, '-30 day')
                   AND o.status = 'Completed'
WHERE c.deleted_at IS NULL 
GROUP BY c.customer_id, c.customer_name, c.segment;
