-- View: vw_product_performance
-- Purpose: Evaluate 360-degree product velocity, revenue contribution, order volume, and profitability
-- Business metric: Total product sales volume, gross revenue, profit margins, and average order value
-- Updated: Automatically recalculated on every query execution (dynamic logic layer)
-- Used by: Product Management Dashboard, Merchandising Team, Executive Financial Reviews
--
-- Columns:
--   product_id: Unique product catalog identifier
--   product_name: Display name of the product
--   category: Product merchandise classification (e.g., Hardware, Software, Cloud Services)
--   unit_price: Standard catalog unit price
--   unit_cost: Unit production / supplier baseline cost
--   total_orders: Number of distinct completed orders containing this product
--   total_revenue: Cumulative gross revenue generated by the product
--   total_gross_profit: Cumulative gross profit (revenue minus product cost)
--   gross_margin_pct: Profitability percentage ratio ((gross profit / revenue) * 100)
--   avg_order_value: Mean monetary value per order for this product

DROP VIEW IF EXISTS vw_product_performance;

CREATE VIEW vw_product_performance AS
SELECT 
    p.product_id,
    p.product_name,
    p.category,
    p.price AS unit_price,
    p.cost AS unit_cost,
    COUNT(DISTINCT o.order_id) AS total_orders,
    COALESCE(SUM(o.order_amount), 0.0) AS total_revenue,
    COALESCE(SUM(o.order_amount - p.cost), 0.0) AS total_gross_profit,
    ROUND(
        (COALESCE(SUM(o.order_amount - p.cost), 0.0) / NULLIF(SUM(o.order_amount), 0)) * 100.0, 
        2
    ) AS gross_margin_pct,
    ROUND(
        COALESCE(AVG(o.order_amount), 0.0), 
        2
    ) AS avg_order_value
FROM products p
JOIN orders o ON p.product_id = o.product_id
WHERE o.status = 'Completed'
GROUP BY p.product_id, p.product_name, p.category, p.price, p.cost;
